/* eslint-disable no-unused-vars */
/*
*  Esquire frameworks (tm)
*  Sandbox server service
*
*  Copyright(c) 2001, 2025 mir0n&co www.mir0n.me
*  mailto:mir0n.the.programmer@gmail.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* Do not edit the class manually.
*/

const  Service  = require('./Service');
const { Datastore } = require('../sandbox/datastore');
const esq = new Datastore();

/**
* Retrieve list of child tree nodes for the node
*
* id String parent node id or missed to obtain root nodes (optional)
* skip Integer number of nodes to skip (optional)
* take Integer number of nodes to obtain (optional)
* returns List
* */
const esquire = ({ id, skip, take }) => new Promise(
  async (resolve, reject) => {
    try {
      resolve(Service.successResponse(
        esq.esquire( id, skip, take,)
      ))
    } catch (e) {
      reject(Service.rejectResponse(
        e.message || 'Invalid input',
        e.status || 405,
      ));
    }
  },
);
/**
* Open interface to call a specific command, default cmd is 'details' to obtain properties on an entity by its id
*
* id String An id of node or entity, depends on command context
* cmd String a command to process , default 'details' (optional)
* returns Object
* */
const esquireCmd = ({ id, cmd }) => new Promise(
  async (resolve, reject) => {
    try {
      resolve(Service.successResponse(
        esq.esquireCmd( id, cmd,)
      ))
    } catch (e) {
      reject(Service.rejectResponse(
        e.message || 'Invalid input',
        e.status || 405,
      ));
    }
  },
);
/**
* Obtain a dictionary of an entity by its kind
*
* kind Integer an entity kind (optional)
* returns List
* */
const esquireDictionary = ({ kind }) => new Promise(
  async (resolve, reject) => {
    try {
      resolve(Service.successResponse(
        esq.esquireDictionary( kind,)
      ))
    } catch (e) {
      reject(Service.rejectResponse(
        e.message || 'Invalid input',
        e.status || 405,
      ));
    }
  },
);
/**
* Find a node corresponding to the entity's id or name + kind
*
* id String an entity id (optional)
* name String an entity name (optional)
* kind Integer an entity type (optional)
* returns List
* */
const esquireEntityNode = ({ id, name, kind }) => new Promise(
  async (resolve, reject) => {
    try {
      resolve(Service.successResponse(
        esq.esquireEntityNode( id, name, kind,)
      ))
    } catch (e) {
      reject(Service.rejectResponse(
        e.message || 'Invalid input',
        e.status || 405,
      ));
    }
  },
);
/**
* Retrieve a path of a node (a location where a node located in the tree)
*
* id String a node id
* returns List
* */
const esquirePath = ({ id }) => new Promise(
  async (resolve, reject) => {
    try {
      resolve(Service.successResponse(
        esq.esquirePath( id,)
      ))
    } catch (e) {
      reject(Service.rejectResponse(
        e.message || 'Invalid input',
        e.status || 405,
      ));
    }
  },
);

module.exports = {
  esquire,
  esquireCmd,
  esquireDictionary,
  esquireEntityNode,
  esquirePath,
};
