/**
 *  Esquire frameworks (tm)
 *  Sandbox rest client
 *
 * Copyright(c) 2021, 2025 mir0n&co www.mir0n.me
 * mailto:mir0n.the.programmer@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */


/**
 * Tree entity field metadata
 */
export interface EsqEntityField { 
    /**
     * name of the field
     */
    name?: string;
    /**
     * position in the sorting order
     */
    sort?: number;
    /**
     * GUI field label
     */
    label?: string;
    /**
     * Type of field data
     */
    type?: EsqEntityField.TypeEnum;
    /**
     * GUI tooltip over the field
     */
    tooltip?: string;
    /**
     * possible values in dropdown list UI element
     */
    listvalues?: Array<string>;
    /**
     * Determines whether the field value can be null
     */
    nullable?: boolean;
    /**
     * a meaning of null value for UI representation
     */
    nullmeaning?: string;
    /**
     * a validation regex for UI input
     */
    validation?: string;
    /**
     * an UI layer of the filed
     */
    layer?: number;
    /**
     * A bitmap (0)hidden (1)view (3)full
     */
    readwrite?: EsqEntityField.ReadwriteEnum;
    /**
     * For listvalues field type only - a kind of entities represented in the list
     */
    listvalues_kind?: number;
}
export namespace EsqEntityField {
    export const TypeEnum = {
        String: 'string',
        Double: 'double',
        Flag: 'flag',
        Listvalues: 'listvalues',
        Href: 'href',
        Tablist: 'tablist',
        Image: 'image'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
    export const ReadwriteEnum = {
        NUMBER_0: 0,
        NUMBER_1: 1,
        NUMBER_3: 3
    } as const;
    export type ReadwriteEnum = typeof ReadwriteEnum[keyof typeof ReadwriteEnum];
}


